"""
The UPnP files come from:
https://openconnectivity.org/developer/specifications/upnp-resources/upnp/
(with some manual corrections to fix invalid sections)
"""

upnp_service_files = [
    (
        "input/upnp_specs/home_automation/lighting_control/service/Dimming1.xml",
        "dimming",
    ),
    (
        "input/upnp_specs/home_automation/lighting_control/service/SwitchPower1.xml",
        "switch-power",
    ),
    (
        "input/upnp_specs/home_automation/hvac/service/ControlValve1.xml",
        "control-valve",
    ),
    (
        "input/upnp_specs/home_automation/hvac/service/FanSpeed1.xml",
        "fan-speed",
    ),
    (
        "input/upnp_specs/home_automation/hvac/service/HouseStatus1.xml",
        "house-status",
    ),
    (
        "input/upnp_specs/home_automation/hvac/service/HVAC_FanOperatingMode1.xml",
        "hvac-fan-operating-mode",
    ),
    (
        "input/upnp_specs/home_automation/hvac/service/HVAC_SetpointSchedule1.xml",
        "hvac-setpoint-schedule",
    ),
    (
        "input/upnp_specs/home_automation/hvac/service/HVAC_UserOperatingMode1.xml",
        "hvac-user-operating-mode",
    ),
    (
        "input/upnp_specs/home_automation/hvac/service/TemperatureSensor1.xml",
        "temperature-sensor",
    ),
    (
        "input/upnp_specs/home_automation/hvac/service/TemperatureSetpoint1.xml",
        "temperature-setpoint",
    ),
    (
        "input/upnp_specs/home_automation/digital_security_camera/service/DigitalSecurityCameraMotionImage1.xml",
        "digital-security-camera-motion-image",
    ),
    (
        "input/upnp_specs/home_automation/digital_security_camera/service/DigitalSecurityCameraSettings1.xml",
        "digital-security-camera-settings",
    ),
    (
        "input/upnp_specs/home_automation/digital_security_camera/service/DigitalSecurityCameraStillImage1.xml",
        "digital-security-camera-still-image",
    ),
    (
        "input/upnp_specs/home_automation/solar-protection-blind/service/TwoWayMotionMotor1.xml",
        "two-way-motion-motor",
    ),
    (
        "input/upnp_specs/printer/service/printbasic1.xml",
        "print-basic",
    ),
    (
        "input/upnp_specs/printer/service/printenhanced1.xml",
        "print-enhanced",
    ),
    (
        "input/upnp_specs/cloud_proxy/service/CloudTransport1.xml",
        "cloud-transport",
    ),
    (
        "input/upnp_specs/cloud_proxy/service/CloudProxy1.xml",
        "cloud-proxy",
    ),
    (
        "input/upnp_specs/device_management/service/BasicManagement2.xml",
        "basic-management",
    ),
    (
        "input/upnp_specs/device_management/service/ConfigurationManagement2.xml",
        "configuration-management",
    ),
    (
        "input/upnp_specs/device_management/service/DeviceProtection1.xml",
        "device-protection",
    ),
    (
        "input/upnp_specs/device_management/service/SoftwareManagement2.xml",
        "software-management",
    ),
    (
        "input/upnp_specs/multi_screen/Service/ApplicationManagement1.xml",
        "application-management",
    ),
    (
        "input/upnp_specs/multi_screen/Service/ApplicationManagement2.xml",
        "application-management-2",
    ),
    (
        "input/upnp_specs/scanner/service/ExternalActivity1.xml",
        "external-activity",
    ),
    (
        "input/upnp_specs/scanner/service/Scan1.xml",
        "scan",
    ),
    (
        "input/upnp_specs/scanner/service/Feeder1.xml",
        "feeder",
    ),
    (
        "input/upnp_specs/iot_management_and_control/service/SensorTransportGeneric1.xml",
        "sensor-transport-generic",
    ),
    (
        "input/upnp_specs/iot_management_and_control/service/DataStore1.xml",
        "data-store",
    ),
    (
        "input/upnp_specs/telephony/service/AddressBook1.xml",
        "address-book",
    ),
    (
        "input/upnp_specs/telephony/service/Calendar1.xml",
        "calendar",
    ),
    (
        "input/upnp_specs/telephony/service/CallManagement2.xml",
        "call-management",
    ),
    (
        "input/upnp_specs/telephony/service/MediaManagement2.xml",
        "media-management",
    ),
    (
        "input/upnp_specs/telephony/service/Messaging2.xml",
        "messaging",
    ),
    (
        "input/upnp_specs/telephony/service/Presence1.xml",
        "presence",
    ),
    (
        "input/upnp_specs/networking/igd/DeviceProtection1.xml",
        "device-protection",
    ),
    (
        "input/upnp_specs/networking/igd/LANHostConfigManagement1.xml",
        "lan-host-config-management",
    ),
    (
        "input/upnp_specs/networking/igd/Layer3Forwarding1.xml",
        "layer-3-forwarding",
    ),
    (
        "input/upnp_specs/networking/igd/WANCableLinkConfig1.xml",
        "wan-cable-link-config",
    ),
    (
        "input/upnp_specs/networking/igd/WANCommonInterfaceConfig1.xml",
        "wan-common-interface-config",
    ),
    (
        "input/upnp_specs/networking/igd/WANDSLLinkConfig1.xml",
        "wan-dsl-link-config",
    ),
    (
        "input/upnp_specs/networking/igd/WANEthernetLinkConfig1.xml",
        "wan-ethernet-link-config",
    ),
    (
        "input/upnp_specs/networking/igd/WANIPConnection1.xml",
        "wan-ip-connection-1",
    ),
    (
        "input/upnp_specs/networking/igd/WANIPConnection2.xml",
        "wan-ip-connection-2",
    ),
    (
        "input/upnp_specs/networking/igd/WANIPv6FirewallControl1.xml",
        "wan-ipv6-firewall-control",
    ),
    (
        "input/upnp_specs/networking/igd/WANPOTSLinkConfig1.xml",
        "wan-pots-link-config",
    ),
    (
        "input/upnp_specs/networking/igd/WANPPPConnection1.xml",
        "wan-ppp-connection",
    ),
    (
        "input/upnp_specs/networking/wlan-access-point/service/LinkAuthentication1.xml",
        "link-authentication",
    ),
    (
        "input/upnp_specs/networking/wlan-access-point/service/RadiusClient1.xml",
        "radius-client",
    ),
    (
        "input/upnp_specs/networking/wlan-access-point/service/WLANConfiguration1.xml",
        "wlan-configuration",
    ),
    (
        "input/upnp_specs/remote_access/InboundConnectionConfig1.xml",
        "inbound-connection-config",
    ),
    (
        "input/upnp_specs/remote_access/RADAConfig2.xml",
        "rada-config",
    ),
    (
        "input/upnp_specs/remote_access/RADASync2.xml",
        "rada-sync",
    ),
    (
        "input/upnp_specs/remote_access/RATAConfig1.xml",
        "rata-config",
    ),
    (
        "input/upnp_specs/remoting/RemoteUIClient1.xml",
        "remote-ui-client",
    ),
    (
        "input/upnp_specs/remoting/RemoteUIServer1.xml",
        "remote-ui-server",
    ),
    (
        "input/upnp_specs/audio_video/service/AVTransport3.xml",
        "av-transport",
    ),
    (
        "input/upnp_specs/audio_video/service/ConnectionManager3.xml",
        "connection-manager",
    ),
    (
        "input/upnp_specs/audio_video/service/ContentDirectory4.xml",
        "content-directory",
    ),
    (
        "input/upnp_specs/audio_video/service/RenderingControl3.xml",
        "rendering-control",
    ),
    (
        "input/upnp_specs/audio_video/service/ScheduledRecording2.xml",
        "scheduled-recording",
    ),
]
